### PR TITLE
Add Fluidd as an alternative interface to Mainsail

### PR DESCRIPTION
**Pull request by jbatonnet**
Add latest version of Fluidd (v1.31.1) as an alternative to Mainsail
Adjust nginx configuration to expose Fluidd on port 4408 (same as newer Creality printers)

### CODE REVIEW

**Comment by utkabobr** [comment]
It's also required to modify update.sh script, I'll test it and merge

**Comment by jbatonnet** [comment]
Yep I missed it, it's updated

**Comment by weekendkoder** [comment]
Is it possible to have both ? (of course maintaining both is not welcomed, i guess). And switch between via different ports ?

**Comment by utkabobr** [comment]
> Is it possible to have both ? (of course maintaining both is not welcomed, i guess). And switch between via different ports ?

Yes, it's configured like that in the pull request

**Pull request merged**
